run('./setup.m');
% % run('./train_phase.m');
fprintf('Loading variables...\n');
load([outputDir, '/', 'vars.m'], '-mat');
fprintf('Loading frames...\n');
load([outputDir, '/', 'raw_frames.m'], '-mat');
fprintf('Loading descriptors...\n');
load([outputDir, '/', 'raw_descs.m'], '-mat');
% fprintf('Loading image dataset...\n');
% load([outputDir, '/', 'imdb.m'], '-mat');
fprintf('Loading vocabulary...\n');
load([outputDir, '/', 'vocab4_500.m'], '-mat');
vocab = vocab4;
fprintf('Loading kdtree 10e5 - 1000 words...\n');
load([outputDir, '/', 'kdtree5_1000.m'], '-mat');
fprintf('Loading visual words of each image in dataset...\n');
load([outputDir, '/', 'imgInvidualVisualWords5_1000.m'], '-mat');
fprintf('Loading idf weighting...\n');
load([outputDir, '/', 'idf.m'], '-mat');
fprintf('Loading inverted index...\n');
load([outputDir, '/', 'invertedIdx_idf_l2.m'], '-mat');
vars.outputDir = outputDir;
vars.datasetUrl = datasetUrl;
vars.mergedDatasetUrl = mergedDatasetUrl;
vars.testDatasetUrl = testDatasetUrl;
queryImg([testDatasetUrl, '904.jpg'], 0, 0, 1, 1, kdtree, vocab, idf, invertedIdx_idf_l2, vars, frames, descs, imgInvidualVisualWords);